### ISSUE TITLE
Hackage publication TODO

### ISSUE THREAD

**Issue by tchoutri** [tchoutri/pg-entity#17]
- [x] Have pg-transact updated and uploaded on Hackage
- [x] Have hspec-pg-transact updated and uploaded on Hackage
- [x] Have a full tutorial
